### ISSUE TITLE
Please change the submodule URL

### ISSUE THREAD

**Issue by ghost** [wesleywerner/nova-pinball#1]
When running `git clone --recursive`, the submodule's URL is the ssh URL. That prevents the clone from succeeding for most users. Per the [git-scm](https://git-scm.com/book/en/v2/Git-Tools-Submodules) book:

> NOTE
> 
> Since the URL in the .gitmodules file is what other people will first try to clone/fetch from, make sure to use a URL that they can access if possible. For example, if you use a different URL to push to than others would to pull from, use the one that others have access to. You can overwrite this value locally with `git config submodule.DbConnector.url PRIVATE_URL` for your own use. When applicable, a relative URL can be helpful.

The solution is to modify .gitmodules as follows:

``` diff
diff --git a/.gitmodules b/.gitmodules
index 369c9c5..24ba480 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,3 +1,3 @@
 [submodule "nova-pinball-engine"]
        path = nova-pinball-engine
-       url = git@github.com:wesleywerner/nova-pinball-engine.git
+       url = https://github.com/wesleywerner/nova-pinball-engine.git
```

and if necessary, to configure your local git as indicated above.

**Comment by wesleywerner** [comment]
Thanks for the comment, I will be doing this some time :+1:

**Comment by wesleywerner** [comment]
Done - thanks again.
